replicaCount: 2

image:
  repository: abudev22/todo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000
  nodePort: 30000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
