replicaCount: 3

image:
  repository: abudev22/todo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
