apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: todo-release
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: charts/todoapp-chart  # Adjust this path to match your chart's location in the repo
      sourceRef:
        kind: GitRepository
        name: todo-helm
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2