apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: todo-release
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/todoapp-chart
      version: 1.0.0
      sourceRef:
        kind: GitRepository
        name: todo-helm
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2